---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Global
- type: document
  path: site/global.md
  label: Global
- type: heading
  label: Pages
- type: document
  path: site/index.md
  label: Home
- type: document
  path: site/products.md
  label: Products
- type: document
  path: site/testimonials.md
  label: Testimonials
- type: document
  path: site/about.md
  label: About
- type: document
  path: site/contact.md
  label: Contact
- type: heading
  label: Collections
- type: directory
  path: site/testimonials
  label: Testimonials
  create: documents
  match: "*"
  templates:
  - testimonial
- type: directory
  path: site/products
  label: Products
  create: documents
  match: "*"
  templates:
  - product
- type: directory
  path: site/blog
  label: Blog posts
  create: documents
  match: "*"
  templates:
  - blog-post
upload_dir: public/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
