---
label: Global config
hide_body: true
fields:
- type: text
  name: site-name
  label: Site name
- name: nav
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Title
  - name: url
    type: text
    config:
      required: false
    label: URL
  config:
    min: 
    max: 
    labelField: 
  label: Navigation
- name: footer
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Footer
pages:
- site/global.md
