---
label: Global config
hide_body: true
fields:
- type: text
  name: site-name
  label: Site name
- name: nav
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Title
  - name: url
    type: text
    config:
      required: false
    label: URL
  config:
    min: 
    max: 
    labelField: 
  label: Navigation
- name: footer
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Footer
- name: social_links
  type: field_group_list
  fields:
  - name: url
    type: text
    config:
      required: true
    label: URL
    description: The web URL to this social account
  - name: icon
    type: file
    config:
      maxSize: 64
    label: Icon
    description: The icon file to use for this social account
  config:
    min: 
    max: 
    labelField: 
  label: Social links
  description: A list of links to social accounts
pages:
- site/global.md
