---
label: Product
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
    min: 0
    max: 200
  label: Title
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
    min: 0
    max: 1000
  label: Description
- type: datetime
  name: publish_date
  label: Publish date
  default: now
- type: boolean
  name: published
  label: Published
- name: product_images
  type: field_group_list
  fields:
  - name: image
    type: file
    config:
      maxSize: 64
    label: Image
  - name: alt
    type: text
    config:
      required: true
      min: 0
      max: 200
    label: Alt
  config:
    min: 0
    max: 10
    labelField: 
  label: Product images
pages:
- site/products/mokopuna-books.md
